### PR TITLE
Guardrails request config validation

### LINKED ISSUE #352: Model type and endpoint mismatch causes 500
## Describe the bug

Currently when a request is sent for a particular standalone detector endpoint, for example `contents`, but the model used is of a different type, e.g.`chat`, then instead of a `400`, we are getting a `500` response.

## Sample Code

```
curl --request POST \
  --url http://localhost:8038/api/v2/text/detection/content \
  --header 'Content-Type: application/json' \
  --data '{
  "detectors": {
    "chat-type-detector-id": {
			"threshold": 0.0
		}
  },
  "content":"Your email is test@ibm.com! Hi, Only the next instance of email will be processed. test@ibm.com. Your SSN is 123-45-6789."
}'
```

## Expected behavior

`400` status code with proper mismatch error

## Observed behavior

```
{
	"code": 500,
	"details": "unexpected error occurred while processing request"
}
```

### PR DESCRIPTION
**Pull request by mdevino**
Closes #352, and also adds appropriate integration tests.

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+    for detector_id in detector_ids {
+        // validate detectors
+        match orchestrator_detectors.get(detector_id) {
+            Some(detector_config) => {
+                if !allowed_detector_types.contains(&detector_config.r#type) {
+                    let error = Error::Validation(format!(
+                        "{}: detector is not supported on this endpoint",
+                        detector_id
+                    ));
+                    error!(%error, "invalid detector on request");
```
Comment (mdevino) [inline src/utils.rs:47]: Should we add the given and allowed detector types to the message?

e.g.: "Invalid detector type: TextContents. Expected [TextChat, TextGeneration]"

File: src/utils.rs [hunk 2]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+    let detector_ids = request_detectors.keys();
+    for detector_id in detector_ids {
+        // validate detectors
+        match orchestrator_detectors.get(detector_id) {
+            Some(detector_config) => {
+                if !allowed_detector_types.contains(&detector_config.r#type) {
+                    let error = Error::Validation(format!(
+                        "{}: detector is not supported on this endpoint",
+                        detector_id
+                    ));
```
Comment (declark1) [inline src/utils.rs:46]: nit: reword error message format for consistency with other error messages

```suggestion
                    let error = Error::Validation(format!(
                        "detector `{detector_id}` is not supported by this endpoint"
                    ));
```

File: src/utils.rs [hunk 3]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+                    error!(%error, "invalid detector on request");
+                    return Err(error);
+                }
+                if !allows_whole_doc_chunker && detector_config.chunker_id == whole_doc_chunker_id {
+                    let error = Error::Validation(format!(
+                        "{}: detector is associated with whole_doc_chunker, which is not supported on this endpoint",
+                        detector_id
+                    ));
```
Comment (declark1) [inline src/utils.rs:54]: nit: reword error message format for consistency with other error messages

```suggestion
                    let error = Error::Validation(format!(
                        "detector `{detector_id}` uses chunker `whole_doc_chunker`, which is not supported by this endpoint"
                    ));
```

File: src/utils.rs [hunk 4]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+                    error!(%error, "detector with invalid chunker on request");
+                    return Err(error);
+                }
+            }
+            None => {
+                let error = Error::DetectorNotFound(detector_id.clone());
+                error!(%error, "detector not found");
```
Comment (declark1) [inline src/utils.rs:61]: nit: error Display impl already provides descriptive message
```suggestion
                error!("{error}");
```

File: src/utils.rs [hunk 5]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+                    ));
+                    error!(%error, "invalid detector on request");
+                    return Err(error);
+                }
+                if !allows_whole_doc_chunker && detector_config.chunker_id == whole_doc_chunker_id {
+                    let error = Error::Validation(format!(
+                        "{}: detector is associated with whole_doc_chunker, which is not supported on this endpoint",
+                        detector_id
+                    ));
+                    error!(%error, "detector with invalid chunker on request");
```
Comment (declark1) [inline src/utils.rs:55]: nit: error Display impl already provides descriptive message
```suggestion
                    error!("{error}");
```

File: src/utils.rs (hunk 1 above)
Comment (declark1) [inline src/utils.rs:47]: nit: error Display impl already provides descriptive message
```suggestion
                    error!("{error}");
```

File: src/utils.rs [hunk 6]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
         Uri::try_from(self.to_string()).unwrap()
     }
 }
+
+/// Validates guardrails on request.
+pub fn validate_guardrails(
```
Comment (declark1) [inline src/utils.rs:30]: Actually, let's just name this `validate_detectors` since it aligns better with what it does. Can you move it to `orchestrator/common/utils.rs`?

File: src/utils.rs [hunk 7]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+    request_detectors: &HashMap<String, DetectorParams>,
+    orchestrator_detectors: &HashMap<String, DetectorConfig>,
+    allowed_detector_types: Vec<DetectorType>,
```
Comment (declark1) [inline src/utils.rs:33]: nit: `allowed_detector_types` should be a slice instead of a `Vec`

File: src/utils.rs [hunk 8]
```diff
@@ -15,3 +25,43 @@ impl AsUriExt for Url {
...
+    allows_whole_doc_chunker: bool,
+) -> Result<(), Error> {
+    let whole_doc_chunker_id = DEFAULT_CHUNKER_ID;
+    let detector_ids = request_detectors.keys();
+    for detector_id in detector_ids {
```
Comment (declark1) [inline src/utils.rs:38]: nit: just iterate over `request_detectors.keys()` directly instead of assigning to a variable. I would also rename `request_detectors` to simply `detectors`.

**Review by declark1 — CHANGES_REQUESTED** [review]
Thanks @mdevino. I left some nit comments inline but otherwise looks good.

**Review by declark1 — COMMENTED** [review]
One additional nit that I forgot to comment earlier, otherwise looks good

The `if !detectors.is_empty()` conditionals aren't needed; if empty, `validate_detectors()` just returns `Ok(())`

**Comment by mdevino** [comment]
> One additional nit that I forgot to comment earlier, otherwise looks good
> 
> The `if !detectors.is_empty()` conditionals aren't needed; if empty, `validate_detectors()` just returns `Ok(())`

Nice catch! Fixed.

**Review by declark1 — APPROVED** [review]
LGTM, thanks!

**Comment by declark1** [comment]
Hmm, does this need to be rebased?

**Comment by mdevino** [comment]
> Hmm, does this need to be rebased?

It doesn't seem so:

image

I started working on this when you were halfway through #355, so I had to rebase at some point and resolve conflicts. That's when the extra commits showed up.
